<?php
# MetInfo Enterprise Content Management System 
# Copyright (C) MetInfo Co.,Ltd (http://www.metinfo.cn). All rights reserved.

defined('IN_MET') or exit('No permission');

define ('TEM_INSTALL_VER', '1.000');

class install {
	function dosql(){
		global $_M;		
		
$sql = array (
  0 => 'pos =\'0\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_head\',value=\'\',defaultvalue=\'\',valueinfo =\'顶部设置\',tips=\'\',bigclass =\'0\'',
  1 => 'pos =\'1\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_index_product\',value=\'\',defaultvalue=\'\',valueinfo =\'首页产品区块\',tips=\'\',bigclass =\'0\'',
  2 => 'pos =\'3\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'news_bar\',value=\'\',defaultvalue=\'\',valueinfo =\'文章模块\',tips=\'\',bigclass =\'0\'',
  3 => 'pos =\'2\',no_order=\'1\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_download\',value=\'\',defaultvalue=\'\',valueinfo =\'下载模块\',tips=\'\',bigclass =\'0\'',
  4 => 'pos =\'0\',no_order=\'2\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'navbarok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'下拉菜单\',tips=\'\',bigclass =\'388\'',
  5 => 'pos =\'1\',no_order=\'2\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_title\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'区块标题\',tips=\'填0隐藏\',bigclass =\'405\'',
  6 => 'pos =\'3\',no_order=\'2\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'bar_column3_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'三级栏目开关\',tips=\'除开产品模块以外的侧栏\',bigclass =\'435\'',
  7 => 'pos =\'2\',no_order=\'2\',type=\'2\',style=\'3\',selectd=\'\',name =\'download\',value=\'立即下载\',defaultvalue=\'立即下载\',valueinfo =\'按钮文字\',tips=\'\',bigclass =\'442\'',
  8 => 'pos =\'2\',no_order=\'3\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_img\',value=\'\',defaultvalue=\'\',valueinfo =\'图片模块\',tips=\'\',bigclass =\'0\'',
  9 => 'pos =\'0\',no_order=\'3\',type=\'2\',style=\'3\',selectd=\'\',name =\'nav_ml\',value=\'10\',defaultvalue=\'10\',valueinfo =\'导航间距\',tips=\'默认是10，仅支持5的倍数（0/5/10/15/20...最大50）<br/>不同网站的导航数量不同，根据需求适当调整间距，让网站更协调。\',bigclass =\'388\'',
  10 => 'pos =\'1\',no_order=\'3\',type=\'3\',style=\'3\',selectd=\'\',name =\'index_product_desc\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'区块描述\',tips=\'填0隐藏\',bigclass =\'405\'',
  11 => 'pos =\'3\',no_order=\'3\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'bar_column_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏栏目开关\',tips=\'除开产品模块以外的侧栏\',bigclass =\'435\'',
  12 => 'pos =\'2\',no_order=\'4\',type=\'4\',style=\'3\',selectd=\'$M$浏览模式$T$1$M$详情模式$T$0\',name =\'img_listlook_style\',value=\'1\',defaultvalue=\'1\',valueinfo =\'查看模式\',tips=\'浏览模式为在列表页浏览图片，详情模式为点击进入详情页\',bigclass =\'352\'',
  13 => 'pos =\'0\',no_order=\'4\',type=\'2\',style=\'3\',selectd=\'\',name =\'nav_all\',value=\'全部\',defaultvalue=\'全部\',valueinfo =\'移动端下拉菜单全部\',tips=\'仅在手机端显示，简介模块不展示，填0隐藏\',bigclass =\'388\'',
  14 => 'pos =\'1\',no_order=\'4\',type=\'6\',style=\'3\',selectd=\'\',name =\'index_product_id\',value=\'\',defaultvalue=\'\',valueinfo =\'调用栏目\',tips=\'调用指定栏目下的子栏目的图片，标题，描述，及该栏目下列表的图片，标题\',bigclass =\'405\'',
  15 => 'pos =\'3\',no_order=\'4\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'news_bar_list_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏列表开关\',tips=\'\',bigclass =\'435\'',
  16 => 'pos =\'0\',no_order=\'5\',type=\'4\',style=\'3\',selectd=\'$M$头部$T$1$M$底部$T$0\',name =\'langlist_position\',value=\'1\',defaultvalue=\'1\',valueinfo =\'多语言位置\',tips=\'\',bigclass =\'388\'',
  17 => 'pos =\'2\',no_order=\'5\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_job\',value=\'\',defaultvalue=\'\',valueinfo =\'招聘模块\',tips=\'\',bigclass =\'0\'',
  18 => 'pos =\'1\',no_order=\'5\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_allnum\',value=\'4\',defaultvalue=\'4\',valueinfo =\'调用导航栏目条数\',tips=\'建议4个\',bigclass =\'405\'',
  19 => 'pos =\'3\',no_order=\'5\',type=\'2\',style=\'3\',selectd=\'\',name =\'news_bar_list_title\',value=\'为您推荐\',defaultvalue=\'为您推荐\',valueinfo =\'侧栏文章列表标题\',tips=\'\',bigclass =\'435\'',
  20 => 'pos =\'0\',no_order=\'6\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'langlist1_icon_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'语言国旗开关\',tips=\'\',bigclass =\'388\'',
  21 => 'pos =\'2\',no_order=\'6\',type=\'2\',style=\'3\',selectd=\'\',name =\'cvtitle\',value=\'在线应聘\',defaultvalue=\'在线应聘\',valueinfo =\'按钮文字\',tips=\'\',bigclass =\'403\'',
  22 => 'pos =\'1\',no_order=\'6\',type=\'4\',style=\'3\',selectd=\'全部$T$all$M$推荐$T$com\',name =\'index_product_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'列表调用类型\',tips=\'列表信息调用类型，【推荐】可以在添加或管理文章列表时设置。\',bigclass =\'405\'',
  23 => 'pos =\'3\',no_order=\'6\',type=\'6\',style=\'3\',selectd=\'\',name =\'sidebar_newslist_idid\',value=\'\',defaultvalue=\'\',valueinfo =\'图文列表调用选择\',tips=\'\',bigclass =\'435\'',
  24 => 'pos =\'2\',no_order=\'7\',type=\'1\',style=\'3\',selectd=\'\',name =\'subcolumn_nav\',value=\'\',defaultvalue=\'\',valueinfo =\'子栏目设置\',tips=\'\',bigclass =\'0\'',
  25 => 'pos =\'0\',no_order=\'7\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_position\',value=\'\',defaultvalue=\'\',valueinfo =\'当前位置\',tips=\'\',bigclass =\'0\'',
  26 => 'pos =\'1\',no_order=\'7\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_img_w\',value=\'800\',defaultvalue=\'800\',valueinfo =\'左侧子栏目缩略图宽\',tips=\'默认为800px\',bigclass =\'405\'',
  27 => 'pos =\'3\',no_order=\'7\',type=\'2\',style=\'3\',selectd=\'\',name =\'sidebar_newslist_num\',value=\'3\',defaultvalue=\'3\',valueinfo =\'侧栏列表数量\',tips=\'\',bigclass =\'435\'',
  28 => 'pos =\'2\',no_order=\'8\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'tagshow_2\',value=\'1\',defaultvalue=\'1\',valueinfo =\'区块开关\',tips=\'\',bigclass =\'354\'',
  29 => 'pos =\'0\',no_order=\'8\',type=\'2\',style=\'3\',selectd=\'\',name =\'position_text\',value=\'你的位置\',defaultvalue=\'你的位置\',valueinfo =\'当前位置标题\',tips=\'\',bigclass =\'356\'',
  30 => 'pos =\'1\',no_order=\'8\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_img_h\',value=\'500\',defaultvalue=\'500\',valueinfo =\'左侧子栏目缩略图高\',tips=\'默认为500px\',bigclass =\'405\'',
  31 => 'pos =\'3\',no_order=\'8\',type=\'4\',style=\'3\',selectd=\'$M$全部$T$all$M$推荐$T$com\',name =\'news_bar_list_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'侧栏列表类型\',tips=\'\',bigclass =\'435\'',
  32 => 'pos =\'0\',no_order=\'9\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'tagshow_1\',value=\'1\',defaultvalue=\'1\',valueinfo =\'区域开关\',tips=\'\',bigclass =\'356\'',
  33 => 'pos =\'1\',no_order=\'9\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_moretext\',value=\'了解更多+\',defaultvalue=\'了解更多+\',valueinfo =\'了解更多按钮文本\',tips=\'填0隐藏\',bigclass =\'405\'',
  34 => 'pos =\'2\',no_order=\'9\',type=\'2\',style=\'3\',selectd=\'\',name =\'all\',value=\'全部\',defaultvalue=\'全部\',valueinfo =\'全部文字\',tips=\'填0隐藏\',bigclass =\'354\'',
  35 => 'pos =\'3\',no_order=\'9\',type=\'2\',style=\'3\',selectd=\'\',name =\'all\',value=\'全部\',defaultvalue=\'全部\',valueinfo =\'全部文字\',tips=\'\',bigclass =\'435\'',
  36 => 'pos =\'0\',no_order=\'10\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_foot\',value=\'\',defaultvalue=\'\',valueinfo =\'底部设置\',tips=\'\',bigclass =\'0\'',
  37 => 'pos =\'2\',no_order=\'10\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_news\',value=\'\',defaultvalue=\'\',valueinfo =\'文章模块\',tips=\'\',bigclass =\'0\'',
  38 => 'pos =\'3\',no_order=\'10\',type=\'1\',style=\'3\',selectd=\'\',name =\'downlaod_bar\',value=\'\',defaultvalue=\'\',valueinfo =\'下载模块\',tips=\'\',bigclass =\'0\'',
  39 => 'pos =\'1\',no_order=\'10\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_img_w1\',value=\'350\',defaultvalue=\'350\',valueinfo =\'右侧列表缩略图宽\',tips=\'默认为350px\',bigclass =\'405\'',
  40 => 'pos =\'0\',no_order=\'11\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'link_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'友情链接开关\',tips=\'\',bigclass =\'338\'',
  41 => 'pos =\'2\',no_order=\'11\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'news_imgok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'图片开关\',tips=\'\',bigclass =\'343\'',
  42 => 'pos =\'3\',no_order=\'11\',type=\'2\',style=\'3\',selectd=\'\',name =\'download_bar_list_title\',value=\'为你推荐\',defaultvalue=\'为你推荐\',valueinfo =\'侧栏下载列表标题\',tips=\'\',bigclass =\'345\'',
  43 => 'pos =\'1\',no_order=\'11\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_product_img_h1\',value=\'328\',defaultvalue=\'328\',valueinfo =\'右侧列表缩略图高\',tips=\'默认为328px\',bigclass =\'405\'',
  44 => 'pos =\'0\',no_order=\'12\',type=\'2\',style=\'3\',selectd=\'\',name =\'footlink_title\',value=\'友情链接\',defaultvalue=\'友情链接\',valueinfo =\'友情链接标题\',tips=\'\',bigclass =\'338\'',
  45 => 'pos =\'3\',no_order=\'12\',type=\'2\',style=\'3\',selectd=\'\',name =\'sidebar_downloadlist_num\',value=\'5\',defaultvalue=\'5\',valueinfo =\'侧栏下载列表数量\',tips=\'\',bigclass =\'345\'',
  46 => 'pos =\'1\',no_order=\'12\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_index_about\',value=\'\',defaultvalue=\'\',valueinfo =\'首页简介区块\',tips=\'\',bigclass =\'0\'',
  47 => 'pos =\'2\',no_order=\'12\',type=\'1\',style=\'3\',selectd=\'\',name =\'para_search\',value=\'\',defaultvalue=\'\',valueinfo =\'搜索模块\',tips=\'\',bigclass =\'0\'',
  48 => 'pos =\'0\',no_order=\'13\',type=\'4\',style=\'3\',selectd=\'$M$底部$T$0$M$顶部$T$1\',name =\'cn1_position\',value=\'0\',defaultvalue=\'0\',valueinfo =\'简繁体切换按钮位置\',tips=\'\',bigclass =\'338\'',
  49 => 'pos =\'3\',no_order=\'13\',type=\'4\',style=\'3\',selectd=\'$M$全部$T$all$M$推荐$T$com\',name =\'download_bar_list_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'侧栏列表下载类型\',tips=\'\',bigclass =\'345\'',
  50 => 'pos =\'1\',no_order=\'13\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_about_title\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'区块标题\',tips=\'填0隐藏\',bigclass =\'431\'',
  51 => 'pos =\'2\',no_order=\'13\',type=\'4\',style=\'3\',selectd=\'非全屏$T$1$M$全屏$T$0\',name =\'type\',value=\'1\',defaultvalue=\'1\',valueinfo =\'是否全屏展示\',tips=\'默认非全屏\',bigclass =\'475\'',
  52 => 'pos =\'0\',no_order=\'14\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'cn1_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'简繁体切换开关\',tips=\'\',bigclass =\'338\'',
  53 => 'pos =\'3\',no_order=\'14\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'download_column3_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'三级栏目开关\',tips=\'\',bigclass =\'345\'',
  54 => 'pos =\'1\',no_order=\'14\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_about_desc\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'区块描述\',tips=\'填0隐藏\',bigclass =\'431\'',
  55 => 'pos =\'2\',no_order=\'14\',type=\'4\',style=\'3\',selectd=\'开启$T$1$M$关闭$T$0\',name =\'attr_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'参数开关\',tips=\'默认开启\',bigclass =\'475\'',
  56 => 'pos =\'3\',no_order=\'15\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'downloadsidebar_column_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏栏目开关\',tips=\'\',bigclass =\'345\'',
  57 => 'pos =\'1\',no_order=\'15\',type=\'8\',style=\'3\',selectd=\'\',name =\'home_about_content\',value=\'\',defaultvalue=\'\',valueinfo =\'区块内容\',tips=\'\',bigclass =\'431\'',
  58 => 'pos =\'0\',no_order=\'15\',type=\'9\',style=\'3\',selectd=\'\',name =\'bg_color\',value=\'#292e44\',defaultvalue=\'#292e44\',valueinfo =\'背景颜色\',tips=\'默认#292e44\',bigclass =\'338\'',
  59 => 'pos =\'2\',no_order=\'15\',type=\'4\',style=\'3\',selectd=\'开启$T$1$M$关闭$T$0\',name =\'sort_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'排序开关\',tips=\'默认开启\',bigclass =\'475\'',
  60 => 'pos =\'3\',no_order=\'16\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'sidebar_downloadlist_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏文章列表开关\',tips=\'\',bigclass =\'345\'',
  61 => 'pos =\'0\',no_order=\'16\',type=\'2\',style=\'3\',selectd=\'\',name =\'aboutus_text\',value=\'关注我们\',defaultvalue=\'关注我们\',valueinfo =\'关注我们文字\',tips=\'\',bigclass =\'338\'',
  62 => 'pos =\'2\',no_order=\'16\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_product\',value=\'\',defaultvalue=\'\',valueinfo =\'产品列表\',tips=\'\',bigclass =\'0\'',
  63 => 'pos =\'1\',no_order=\'16\',type=\'7\',style=\'3\',selectd=\'\',name =\'uiBgImage\',value=\'\',defaultvalue=\'\',valueinfo =\'区块背景图\',tips=\'建议宽度1920，高度自适应，移动端截取中间展示\',bigclass =\'431\'',
  64 => 'pos =\'3\',no_order=\'17\',type=\'1\',style=\'3\',selectd=\'\',name =\'img_bar\',value=\'\',defaultvalue=\'\',valueinfo =\'图片模块\',tips=\'\',bigclass =\'0\'',
  65 => 'pos =\'1\',no_order=\'17\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_index_case\',value=\'\',defaultvalue=\'\',valueinfo =\'首页合作伙伴\',tips=\'\',bigclass =\'0\'',
  66 => 'pos =\'0\',no_order=\'17\',type=\'2\',style=\'3\',selectd=\'\',name =\'erweima_one\',value=\'订阅“公众号”\',defaultvalue=\'订阅“公众号”\',valueinfo =\'第一个二维码标题\',tips=\'\',bigclass =\'338\'',
  67 => 'pos =\'3\',no_order=\'18\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'img_bar_list_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏图片列表开关\',tips=\'\',bigclass =\'359\'',
  68 => 'pos =\'1\',no_order=\'18\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_title\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'区块标题\',tips=\'填0隐藏\',bigclass =\'418\'',
  69 => 'pos =\'0\',no_order=\'18\',type=\'2\',style=\'3\',selectd=\'\',name =\'erweima_two\',value=\'扫码咨询\',defaultvalue=\'扫码咨询\',valueinfo =\'第二个二维码标题\',tips=\'\',bigclass =\'338\'',
  70 => 'pos =\'3\',no_order=\'19\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_bar_list_title\',value=\'为您推荐\',defaultvalue=\'为您推荐\',valueinfo =\'侧栏图片列表标题\',tips=\'\',bigclass =\'359\'',
  71 => 'pos =\'1\',no_order=\'19\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_desc\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'区块描述\',tips=\'填0隐藏\',bigclass =\'418\'',
  72 => 'pos =\'0\',no_order=\'19\',type=\'2\',style=\'3\',selectd=\'\',name =\'wooktime_text\',value=\'周一至周五 09：00-18：00\',defaultvalue=\'周一至周五 09：00-18：00\',valueinfo =\'工作时间文字\',tips=\'填0则整行隐藏\',bigclass =\'338\'',
  73 => 'pos =\'3\',no_order=\'20\',type=\'4\',style=\'3\',selectd=\'$M$全部$T$all$M$推荐$T$com\',name =\'img_bar_list_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'侧栏列表图片类型\',tips=\'\',bigclass =\'359\'',
  74 => 'pos =\'1\',no_order=\'20\',type=\'6\',style=\'3\',selectd=\'\',name =\'home_case_id\',value=\'\',defaultvalue=\'\',valueinfo =\'栏目选择\',tips=\'\',bigclass =\'418\'',
  75 => 'pos =\'0\',no_order=\'20\',type=\'7\',style=\'3\',selectd=\'\',name =\'footinfo_wx2\',value=\'\',defaultvalue=\'\',valueinfo =\'第二个二维码\',tips=\'建议尺寸112*112\',bigclass =\'338\'',
  76 => 'pos =\'3\',no_order=\'21\',type=\'2\',style=\'3\',selectd=\'\',name =\'img_bar_list_num\',value=\'5\',defaultvalue=\'5\',valueinfo =\'侧栏列表图片数量\',tips=\'\',bigclass =\'359\'',
  77 => 'pos =\'0\',no_order=\'21\',type=\'1\',style=\'3\',selectd=\'\',name =\'global\',value=\'\',defaultvalue=\'\',valueinfo =\'全局参数\',tips=\'\',bigclass =\'0\'',
  78 => 'pos =\'1\',no_order=\'21\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_num\',value=\'8\',defaultvalue=\'8\',valueinfo =\'调用条数\',tips=\'默认调用8条\',bigclass =\'418\'',
  79 => 'pos =\'3\',no_order=\'22\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'imgbar_column_open\',value=\'1\',defaultvalue=\'1\',valueinfo =\'侧栏栏目开关\',tips=\'\',bigclass =\'359\'',
  80 => 'pos =\'0\',no_order=\'22\',type=\'2\',style=\'3\',selectd=\'\',name =\'met_font\',value=\'\',defaultvalue=\'\',valueinfo =\'页面字体\',tips=\'非特殊语种，建议留空使用模板默认字体\',bigclass =\'395\'',
  81 => 'pos =\'1\',no_order=\'22\',type=\'4\',style=\'3\',selectd=\'全部$T$all$M$推荐$T$com\',name =\'home_case_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'调用类型\',tips=\'\',bigclass =\'418\'',
  82 => 'pos =\'3\',no_order=\'23\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'img_column3_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'三级栏目开关\',tips=\'\',bigclass =\'359\'',
  83 => 'pos =\'0\',no_order=\'23\',type=\'2\',style=\'3\',selectd=\'\',name =\'sub_all\',value=\'全部\',defaultvalue=\'全部\',valueinfo =\'页面文字\',tips=\'\',bigclass =\'395\'',
  84 => 'pos =\'1\',no_order=\'23\',type=\'4\',style=\'3\',selectd=\'纯展示$T$0$M$超链接$T$1\',name =\'home_case_linkok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'展示方式\',tips=\'默认为超链接\',bigclass =\'418\'',
  85 => 'pos =\'3\',no_order=\'24\',type=\'1\',style=\'3\',selectd=\'\',name =\'product_bar\',value=\'\',defaultvalue=\'\',valueinfo =\'产品模块侧边栏\',tips=\'\',bigclass =\'0\'',
  86 => 'pos =\'0\',no_order=\'24\',type=\'2\',style=\'3\',selectd=\'\',name =\'page_ajax_next\',value=\'加载更多\',defaultvalue=\'加载更多\',valueinfo =\'分页文字\',tips=\'无刷新分页默认文字\',bigclass =\'395\'',
  87 => 'pos =\'1\',no_order=\'24\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_imgw\',value=\'422\',defaultvalue=\'422\',valueinfo =\'缩略图宽\',tips=\'默认为422px\',bigclass =\'418\'',
  88 => 'pos =\'3\',no_order=\'25\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_sidebar_piclist_title\',value=\'热门推荐\',defaultvalue=\'热门推荐\',valueinfo =\'区块标题\',tips=\'\',bigclass =\'366\'',
  89 => 'pos =\'0\',no_order=\'25\',type=\'2\',style=\'3\',selectd=\'\',name =\'nodata\',value=\'没有数据了\',defaultvalue=\'没有数据了\',valueinfo =\'无数据提示\',tips=\'\',bigclass =\'395\'',
  90 => 'pos =\'1\',no_order=\'25\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_case_imgh\',value=\'415\',defaultvalue=\'415\',valueinfo =\'缩略图高\',tips=\'默认为415px\',bigclass =\'418\'',
  91 => 'pos =\'3\',no_order=\'26\',type=\'2\',style=\'3\',selectd=\'\',name =\'product_sidebar_piclist_num\',value=\'5\',defaultvalue=\'5\',valueinfo =\'调用条数\',tips=\'\',bigclass =\'366\'',
  92 => 'pos =\'1\',no_order=\'26\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_index_news\',value=\'\',defaultvalue=\'\',valueinfo =\'首页新闻区块\',tips=\'\',bigclass =\'0\'',
  93 => 'pos =\'0\',no_order=\'26\',type=\'2\',style=\'3\',selectd=\'\',name =\'search_placeholder\',value=\'请输入内容关键词\',defaultvalue=\'请输入内容关键词\',valueinfo =\'搜索文字\',tips=\'\',bigclass =\'395\'',
  94 => 'pos =\'3\',no_order=\'27\',type=\'4\',style=\'3\',selectd=\'$M$全部$T$all$M$推荐$T$com\',name =\'product_sidebar_piclist_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'调用类型\',tips=\'\',bigclass =\'366\'',
  95 => 'pos =\'1\',no_order=\'27\',type=\'2\',style=\'3\',selectd=\'\',name =\'index_news_title\',value=\'标题\',defaultvalue=\'标题\',valueinfo =\'区块标题\',tips=\'填0隐藏\',bigclass =\'377\'',
  96 => 'pos =\'0\',no_order=\'27\',type=\'9\',style=\'3\',selectd=\'\',name =\'first_color\',value=\'#000000\',defaultvalue=\'#000000\',valueinfo =\'模板主色调\',tips=\'\',bigclass =\'395\'',
  97 => 'pos =\'3\',no_order=\'28\',type=\'4\',style=\'3\',selectd=\'当前一级栏目内容列表$T$1$M$TAG标签聚合$T$0\',name =\'product_sidebar_content\',value=\'1\',defaultvalue=\'1\',valueinfo =\'调用内容\',tips=\'默认调用当前栏目内容列表\',bigclass =\'366\'',
  98 => 'pos =\'1\',no_order=\'28\',type=\'3\',style=\'3\',selectd=\'\',name =\'index_news_desc\',value=\'描述\',defaultvalue=\'描述\',valueinfo =\'区块描述\',tips=\'填0隐藏\',bigclass =\'377\'',
  99 => 'pos =\'0\',no_order=\'28\',type=\'9\',style=\'3\',selectd=\'\',name =\'thirdcolor\',value=\'#1baadb\',defaultvalue=\'#1baadb\',valueinfo =\'模板配色调\',tips=\'\',bigclass =\'395\'',
  100 => 'pos =\'1\',no_order=\'29\',type=\'6\',style=\'3\',selectd=\'\',name =\'home_news1\',value=\'4\',defaultvalue=\'4\',valueinfo =\'调用栏目\',tips=\'调用当前栏目的内容列表\',bigclass =\'377\'',
  101 => 'pos =\'0\',no_order=\'29\',type=\'4\',style=\'3\',selectd=\'当前窗口打开$T$target=_self$M$新窗口打开$T$target=_blank\',name =\'urlnew\',value=\'target=_self\',defaultvalue=\'target=_self\',valueinfo =\'内容列表链接打开方式\',tips=\'列表页链接打开方式可在栏目管理中对每个栏目进行单独设置\',bigclass =\'395\'',
  102 => 'pos =\'0\',no_order=\'30\',type=\'1\',style=\'3\',selectd=\'\',name =\'banner\',value=\'\',defaultvalue=\'\',valueinfo =\'banner设置\',tips=\'\',bigclass =\'0\'',
  103 => 'pos =\'1\',no_order=\'30\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_news_num\',value=\'6\',defaultvalue=\'6\',valueinfo =\'调用条数\',tips=\'默认6条,仅为无图模式生效，有图模式固定调用4条\',bigclass =\'377\'',
  104 => 'pos =\'0\',no_order=\'31\',type=\'4\',style=\'3\',selectd=\'$M$提示$T$1\',name =\'info\',value=\'1\',defaultvalue=\'1\',valueinfo =\'提示\',tips=\'此banner是图片不适合设置高度，如果觉得banner尺寸不合适请更换banner尺寸\',bigclass =\'371\'',
  105 => 'pos =\'1\',no_order=\'31\',type=\'4\',style=\'3\',selectd=\'$M$全部$T$all$M$推荐$T$com\',name =\'home_news_type\',value=\'all\',defaultvalue=\'all\',valueinfo =\'调用类型\',tips=\'\',bigclass =\'377\'',
  106 => 'pos =\'0\',no_order=\'32\',type=\'9\',style=\'3\',selectd=\'\',name =\'page_top_bgcolor\',value=\'#ccc\',defaultvalue=\'#ccc\',valueinfo =\'内页无banner背景色\',tips=\'\',bigclass =\'371\'',
  107 => 'pos =\'1\',no_order=\'32\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_news_img_maxnum\',value=\'54\',defaultvalue=\'54\',valueinfo =\'描述文字字数限制\',tips=\'默认为54个字符\',bigclass =\'377\'',
  108 => 'pos =\'0\',no_order=\'33\',type=\'9\',style=\'3\',selectd=\'\',name =\'bannersub_color\',value=\'#fff\',defaultvalue=\'#fff\',valueinfo =\'内页无banner字体色\',tips=\'\',bigclass =\'371\'',
  109 => 'pos =\'1\',no_order=\'33\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_product_img_w\',value=\'210\',defaultvalue=\'210\',valueinfo =\'图片风格下右边小缩略图宽\',tips=\'默认为210px\',bigclass =\'377\'',
  110 => 'pos =\'0\',no_order=\'34\',type=\'2\',style=\'3\',selectd=\'\',name =\'btn_margin\',value=\'5\',defaultvalue=\'5\',valueinfo =\'电脑端按钮之间的边距\',tips=\'默认为5px\',bigclass =\'371\'',
  111 => 'pos =\'1\',no_order=\'34\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_product_img_h\',value=\'130\',defaultvalue=\'130\',valueinfo =\'图片风格下右边小缩略图高\',tips=\'默认为130px\',bigclass =\'377\'',
  112 => 'pos =\'0\',no_order=\'35\',type=\'2\',style=\'3\',selectd=\'\',name =\'mbtn_margin\',value=\'5\',defaultvalue=\'5\',valueinfo =\'手机端按钮之间的边距\',tips=\'默认为5px\',bigclass =\'371\'',
  113 => 'pos =\'1\',no_order=\'35\',type=\'4\',style=\'3\',selectd=\'无图风格$T$1$M$有图风格$T$0\',name =\'index_news_mytype\',value=\'1\',defaultvalue=\'1\',valueinfo =\'展示风格\',tips=\'默认无图风格\',bigclass =\'377\'',
  114 => 'pos =\'0\',no_order=\'36\',type=\'1\',style=\'3\',selectd=\'\',name =\'met_contact\',value=\'\',defaultvalue=\'\',valueinfo =\'底部联系信息设置\',tips=\'\',bigclass =\'0\'',
  115 => 'pos =\'1\',no_order=\'36\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_product_img_w1\',value=\'636\',defaultvalue=\'636\',valueinfo =\'图片风格下左边缩略图宽\',tips=\'默认为636px\',bigclass =\'377\'',
  116 => 'pos =\'0\',no_order=\'37\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_tel\',value=\'联系我们\',defaultvalue=\'联系我们\',valueinfo =\'联系我们\',tips=\'填0隐藏\',bigclass =\'444\'',
  117 => 'pos =\'1\',no_order=\'37\',type=\'2\',style=\'3\',selectd=\'\',name =\'home_product_img_h1\',value=\'491\',defaultvalue=\'491\',valueinfo =\'图片风格下左边缩略图宽\',tips=\'默认为491px\',bigclass =\'377\'',
  118 => 'pos =\'0\',no_order=\'38\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_dsc\',value=\'\',defaultvalue=\'\',valueinfo =\'描述文字\',tips=\'填0隐藏\',bigclass =\'444\'',
  119 => 'pos =\'0\',no_order=\'39\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_wx_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'微信\',tips=\'\',bigclass =\'444\'',
  120 => 'pos =\'0\',no_order=\'40\',type=\'7\',style=\'3\',selectd=\'\',name =\'footinfo_wx\',value=\'\',defaultvalue=\'\',valueinfo =\'微信二维码\',tips=\'\',bigclass =\'444\'',
  121 => 'pos =\'0\',no_order=\'41\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_qq_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'QQ\',tips=\'\',bigclass =\'444\'',
  122 => 'pos =\'0\',no_order=\'42\',type=\'4\',style=\'3\',selectd=\'$M$个人QQ$T$1$M$企业营销QQ$T$2\',name =\'foot_info_qqtype\',value=\'1\',defaultvalue=\'1\',valueinfo =\'QQ类型\',tips=\'个人QQ和企业营销QQ超链接结构不一样，因此请务必选择正确。\',bigclass =\'444\'',
  123 => 'pos =\'0\',no_order=\'43\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_qq\',value=\'\',defaultvalue=\'\',valueinfo =\'QQ号码\',tips=\'点击QQ链接可直接对话，需要先到 shang.qq.com 免费开通。<br/>企业营销QQ 无需开通\',bigclass =\'444\'',
  124 => 'pos =\'0\',no_order=\'44\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_sina_ok\',value=\'1\',defaultvalue=\'1\',valueinfo =\'新浪微博\',tips=\'\',bigclass =\'444\'',
  125 => 'pos =\'0\',no_order=\'45\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_sina\',value=\'\',defaultvalue=\'\',valueinfo =\'新浪微博网址\',tips=\'请输入微博网址\',bigclass =\'444\'',
  126 => 'pos =\'0\',no_order=\'46\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_twitterok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'twitter（推特）\',tips=\'\',bigclass =\'444\'',
  127 => 'pos =\'0\',no_order=\'47\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_twitter\',value=\'\',defaultvalue=\'\',valueinfo =\'twitter网址\',tips=\'\',bigclass =\'444\'',
  128 => 'pos =\'0\',no_order=\'48\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_googleok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'google+\',tips=\'\',bigclass =\'444\'',
  129 => 'pos =\'0\',no_order=\'49\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_google\',value=\'\',defaultvalue=\'\',valueinfo =\'google+网址\',tips=\'\',bigclass =\'444\'',
  130 => 'pos =\'0\',no_order=\'50\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_facebookok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'Facebook\',tips=\'\',bigclass =\'444\'',
  131 => 'pos =\'0\',no_order=\'51\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_facebook\',value=\'\',defaultvalue=\'\',valueinfo =\'Facebook网址\',tips=\'\',bigclass =\'444\'',
  132 => 'pos =\'0\',no_order=\'52\',type=\'4\',style=\'3\',selectd=\'$M$开启$T$1$M$关闭$T$0\',name =\'footinfo_emailok\',value=\'0\',defaultvalue=\'0\',valueinfo =\'邮箱\',tips=\'\',bigclass =\'444\'',
  133 => 'pos =\'0\',no_order=\'53\',type=\'2\',style=\'3\',selectd=\'\',name =\'footinfo_email\',value=\'\',defaultvalue=\'\',valueinfo =\'邮箱地址\',tips=\'\',bigclass =\'444\'',
);
$no='metv75';
$devices='0';
		$re['sql'] = $sql;
		$re['no'] = $no;
		$re['devices'] = $devices;
		return $re;
	}
}

# This program is an open source system, commercial use, please consciously to purchase commercial license.
# Copyright (C) MetInfo Co., Ltd. (http://www.metinfo.cn). All rights reserved.
?>